# define third-party library paths
# CHANGE YOUR CUDA PATH IF IT IS NOT THIS
CUDA_DIR := /usr/local/cuda
# CHANGE YOUR CUDA ARCH IF IT IS NOT THIS
CUDA_ARCH := -arch=sm_30
# CHANGE YOUR MKL PATH IF IT IS NOT THIS
MKL_DIR := /opt/intel/mkl
# CHANGE YOUR MATLAB PATH IF IT IS NOT THIS
# your mex binary should be located at $(MATLAB_DIR)/bin/mex
MATLAB_DIR := /usr/local
# PUT ALL OTHER INCLUDE AND LIB DIRECTORIES HERE
INCLUDE_DIRS := /usr/local/include /usr/include/python2.7 \
    /usr/local/lib/python2.7/dist-packages/numpy/core/include
LIBRARY_DIRS := /usr/lib /usr/local/lib

# DEFINE THE CXX PATH
CXX=/usr/bin/g++
