/* 
                      DO NOT EDIT THIS FILE!

 it has been automaticaly created by php5/scripts/credits from  
 the information found in the various php5/ext/.../CREDITS and
 php5/sapi/.../CREDITS files 
 
 if you want to change an entry you have to edit the appropriate 
 CREDITS file instead

*/

