#include "caffe/layer.hpp"

namespace caffe {

class LayerBase;

INSTANTIATE_CLASS_3T(Layer, (half_fp), PROTO_TYPES, PROTO_TYPES);
INSTANTIATE_CLASS_3T(Layer, (float), PROTO_TYPES, PROTO_TYPES);
INSTANTIATE_CLASS_3T(Layer, (double), PROTO_TYPES, PROTO_TYPES);
INSTANTIATE_CLASS_3T(Layer, (int8_t), PROTO_TYPES, PROTO_TYPES);
INSTANTIATE_CLASS_3T(Layer, (int16_t), PROTO_TYPES, PROTO_TYPES);
INSTANTIATE_CLASS_3T(Layer, (int32_t), PROTO_TYPES, PROTO_TYPES);
INSTANTIATE_CLASS_3T(Layer, (int64_t), PROTO_TYPES, PROTO_TYPES);


}  // namespace caffe
