#include "caffe/layer.hpp"

namespace caffe {

class LayerBase;

INSTANTIATE_CLASS_3T_GUARDED(Layer, (half_fp), PROTO_TYPES, PROTO_TYPES);
INSTANTIATE_CLASS_3T_GUARDED(Layer, (float), PROTO_TYPES, PROTO_TYPES);
INSTANTIATE_CLASS_3T_GUARDED(Layer, (double), PROTO_TYPES, PROTO_TYPES);
INSTANTIATE_CLASS_3T_GUARDED(Layer, (uint8_t), PROTO_TYPES, PROTO_TYPES);
INSTANTIATE_CLASS_3T_GUARDED(Layer, (uint16_t), PROTO_TYPES, PROTO_TYPES);
INSTANTIATE_CLASS_3T_GUARDED(Layer, (uint32_t), PROTO_TYPES, PROTO_TYPES);
INSTANTIATE_CLASS_3T_GUARDED(Layer, (uint64_t), PROTO_TYPES, PROTO_TYPES);


}  // namespace caffe
