#pragma once

#if defined(_MSC_VER)

#include "common.hpp"

#if !defined(GET_CLASS_GUARD_NAME)
#error "Cannot proceed without the macro GET_CLASS_GUARD_NAME"
#endif

#define FORCE_TO_LINK_CLASS(type) \
    extern char GET_CLASS_GUARD_NAME(type);   \
    static char __##type = GET_CLASS_GUARD_NAME(type);

namespace caffe {

#ifdef CMAKE_BUILD

    // LayerFactory is a special case
    // that does not contain INSTANTIATE_CLASS.
    // Thus it is explicitly included here.
    FORCE_TO_LINK_CLASS(LayerFactory);

    // The content of the following file was generated by CMake.
    #include "caffe/msvc/caffe_classes.hpp"

#endif  // #ifdef CMAKE_BUILD

}   // namespace caffe

#endif

