#ifndef CAFFE_DUMMY_DATA_LAYER_HPP_
#define CAFFE_DUMMY_DATA_LAYER_HPP_

#include <vector>

#include "caffe/blob.hpp"
#include "caffe/filler.hpp"
#include "caffe/layer.hpp"
#include "caffe/proto/caffe.pb.h"

namespace caffe {

/**
 * @brief Provides data to the Net generated by a Filler.
 *
 * TODO(dox): thorough documentation for Forward and proto params.
 */
template <typename Dtype, typename Ctype, typename MIType, typename MOType>
class DummyDataLayer : public Layer<Dtype, Ctype, MIType, MOType> {
 public:
  explicit DummyDataLayer(const LayerParameter& param)
      : Layer<Dtype>(param) {}
  virtual void LayerSetUp(const vector<Blob<Dtype, MIType>*>& bottom,
      const vector<Blob<Dtype, MOType>*>& top);
  // Data layers have no bottoms, so reshaping is trivial.
  virtual void Reshape(const vector<Blob<Dtype, MIType>*>& bottom,
      const vector<Blob<Dtype, MOType>*>& top) {}

  virtual inline const char* type() const { return "DummyData"; }
  virtual inline int_tp ExactNumBottomBlobs() const { return 0; }
  virtual inline int_tp MinTopBlobs() const { return 1; }

 protected:
  virtual void Forward_cpu(const vector<Blob<Dtype, MIType>*>& bottom,
      const vector<Blob<Dtype, MOType>*>& top);
  virtual void Backward_cpu(
      const vector<Blob<Dtype, MOType>*>& top,
      const vector<bool>& propagate_down,
      const vector<Blob<Dtype, MIType>*>& bottom) {}
  virtual void Backward_gpu(
      const vector<Blob<Dtype, MOType>*>& top,
      const vector<bool>& propagate_down,
      const vector<Blob<Dtype, MIType>*>& bottom) {}

  vector<std::shared_ptr<Filler<Dtype> > > fillers_;
  vector<bool> refill_;
};

}  // namespace caffe

#endif  // CAFFE_DUMMY_DATA_LAYER_HPP_
