# Create the header file of classes.
# Essentiall it execute the following command:
# $ grep -r "INSTANTIATE_CLASS" src/caffe/* | cut -d "(" -f "2" | cut -d ")" -f 1 | awk '{ print "FORCE_TO_LINK_CLASS(", $0, ")" }'

if( DEFINED WIN32 )
    message(STATUS "Scanning classes in Caffe...")

    set(CAFFE_CLASS_FILE "${CMAKE_SOURCE_DIR}/include/caffe/msvc/caffe_classes.hpp")
    file(WRITE ${CAFFE_CLASS_FILE}  "// DO NOT modifiy this file! \n"
                                    "// It is automatically generated by CMake. \n"
                                    "// See ${CMAKE_CURRENT_LIST_FILE} for the detail.\n" )
    execute_process(
        COMMAND findstr /S "INSTANTIATE_CLASS" "${CMAKE_SOURCE_DIR}/src/caffe/*" 
        OUTPUT_VARIABLE CAFFE_CLASS_LINES)
    set(FORCE_TO_LINK_CAFFE_CLASSES "")
    
    foreach(CAFFE_CLASS_LINE ${CAFFE_CLASS_LINES} )
        string(STRIP "${CAFFE_CLASS_LINE}" CAFFE_CLASS_LINE )
        string(LENGTH "${CAFFE_CLASS_LINE}" CAFFE_CLASS_LINE_LENGTH )
        if( ${CAFFE_CLASS_LINE_LENGTH} GREATER 0 )
            string(REGEX REPLACE "^.+INSTANTIATE_CLASS" "FORCE_TO_LINK_CLASS" FORCE_TO_LINK_CAFFE_CLASS ${CAFFE_CLASS_LINE})
            list(APPEND FORCE_TO_LINK_CAFFE_CLASSES "${FORCE_TO_LINK_CAFFE_CLASS}\n")
        endif()
    endforeach()
    list(LENGTH FORCE_TO_LINK_CAFFE_CLASSES N_CAFFE_CLASSES)
    file(APPEND ${CAFFE_CLASS_FILE} ${FORCE_TO_LINK_CAFFE_CLASSES})
    
    message(STATUS "Found ${N_CAFFE_CLASSES} classes. Listed in ${CAFFE_CLASS_FILE}.")
endif()
    
